name: Expression
on:
  workflow_dispatch:
      inputs:
       edad:
         description: 'edad'
         required: true
         type: integer
       nombre:
          description: 'tu nombre'
          required: true
          default: 'sebastian'
          type: string
jobs:
  mayor:
        if: ${{ inputs.edad>=18 }}
        runs-on: ubuntu-latest
        steps:
          - name: Ejecucion Script
            run: echo ${{ inputs.nombre }} es mayor de edad
  menor:
        if: ${{ inputs.edad<18 }}
        runs-on: ubuntu-latest
        steps:
          - name: Ejecucion Script
            run: echo ${{ inputs.nombre }} es menor de edad
        
